import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import { Toaster } from "react-hot-toast";
import { QueryProvider } from "@/providers/query-provider";
import { ModalProvider } from "@/providers/modal-provider";
import SocketOnConnect from "@/components/socket-onConnect";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>


        <QueryProvider>
          <ModalProvider />
          <SocketOnConnect />
          {children}

        </QueryProvider>

      </body>
      <Toaster />
    </html>

  );
}
